apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: paperspace
spec:
  schedule: "* * * * *"

  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1

  jobTemplate:
    spec:
      backoffLimit: 0

      template:
        metadata:
          labels:
            app: paperspace
        spec:
          restartPolicy: OnFailure
          containers:
            - name: main
              image: mattfeng/paperspace-availability:0.0.2debug0
              env:
                - name: API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: paperspace-secrets
                      key: api_key

                - name: TEAM_ID
                  valueFrom:
                    secretKeyRef:
                      name: paperspace-secrets
                      key: team_id

                - name: NAMESPACE
                  valueFrom:
                    secretKeyRef:
                      name: paperspace-secrets
                      key: namespace

                - name: MONGO_URI
                  valueFrom:
                    secretKeyRef:
                      name: paperspace-secrets
                      key: mongo_uri
